[package]
name = "rataplay"
version = "1.5.1-beta"
edition = "2024"
description = "A high-performance Rust TUI for YouTube playback and management"
license = "GPL-3.0-only"
homepage = "https://github.com/mojahid8238/Rataplay"
repository = "https://github.com/mojahid8238/Rataplay"
readme = "README.md"
categories = ["multimedia", "terminal-ui"]
keywords = ["youtube", "tui", "mpv", "yt-dlp", "media"]
authors = ["Mojahid <mi8238229@gmail.com>"]

[dependencies]
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "sync", "time", "process", "io-util", "net", "fs", "signal"] }
ratatui = { version = "0.30.0", default-features = false, features = ["crossterm"] }
crossterm = "0.29.0"
image = { version = "0.25.5", default-features = false, features = ["png", "jpeg"] } 
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
toml = { version = "0.8.19", default-features = false, features = ["parse", "display"] }
anyhow = "1.0.95"
clap = { version = "4.5.24", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json"] } 
ratatui-image = { version = "10.0.2", default-features = false, features = ["crossterm"] } 
lru = "0.12.3"
libc = "0.2.155"
souvlaki = "0.7.3"
directories = "6.0.0"
arboard = "3.4.1"
webbrowser = "1.0.1"
log = "0.4"
fern = { version = "0.7", features = ["colored"] }
chrono = "0.4"

[profile.release]
opt-level = 3
lto = true
codegen-units = 16
panic = "abort"
strip = true

[package.metadata.deb]
maintainer = "Mojahid <mi8238229@gmail.com>"
depends = "mpv, yt-dlp"
extended-description = """A high-performance Terminal User Interface for searching, playing, and downloading YouTube videos. Powered by mpv and yt-dlp."""
section = "video"
priority = "optional"
assets = [
    ["target/release/rataplay", "/usr/bin/rataplay", "755"],
    ["man/rataplay.1", "/usr/share/man/man1/rataplay.1", "644"],
]

[package.metadata.generate-rpm]
version = "1.5.1"
description-file = "README.md"
assets = [
    { source = "target/release/rataplay", dest = "/usr/bin/rataplay", mode = "755" },
    { source = "man/rataplay.1", dest = "/usr/share/man/man1/rataplay.1", mode = "644" },
]

[package.metadata.generate-rpm.requires]
mpv = "*"
yt-dlp = "*"


